version: '3.8'

services:
  # app:
  #   container_name: nestjs_app
  #   build:
  #     context: .
  #     dockerfile: .docker/Dockerfile.dev
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - '3000:3000'
  #   environment:
  #     - DATABASE_URL=postgres://postgres:password@db:5432/postgres
  #   depends_on:
  #     - db
  #   command: npm run start:dev
  #   networks:
  #     - app-network

  db:
    container_name: postgres_db
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata:
    driver: local
