# Start from the Node.js image.
FROM node:16-alpine

# Create app directory
WORKDIR /usr/src/app

# Install global npm dependencies
RUN npm install -g @nestjs/cli

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
COPY package*.json ./
RUN npm install

# Bundle app source
COPY . .

# Expose the port the app runs on
EXPOSE 3000

# Start the application using Nest CLI
CMD ["npm", "run", "start:dev"]
